name: Actions CI with Docker Containers inside GitHub's built in Runner

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.31.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose        

      - name: Start up Docker Services
        run: docker-compose up --build -d # Run in detached mode

      - name: Wait 30 seconds for services to finish starting up
        run: sleep 30

      - name: (PRE-TEST) Log memory usage
        run: free -m

      # Need this extra step for GitHub Actions for some reason. When running locally, [docker-compose up --build] is enough to cover everything
      - name: Execute Tests
        run: docker-compose exec test-runner mvn test -Dbrowser=Firefox

      - name: (POST-TEST) Log memory usage
        run: free -m

      - name: Clean up
        run: docker-compose down