name: Actions CI with Docker

on:
  push:
    branches:
      - master
    paths:
      # Only trigger workflow when pushing to master branch with changes to files under these directories and files
      - 'src/**'
      - '.github/workflows/**'
      - 'docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose        

      - name: Start up Docker Services
        run: docker-compose up --build
        timeout-minutes: 2 # This step gets stuck infinitely in GitHub. Add timeout so can move to clean up step

      - name: Clean up
        run: docker-compose down