name: Github Actions CI with Docker Containers

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.31.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose        

      - name: Start up Docker Services
        run: docker-compose up --build -d

      - name: Execute Tests
        run: docker-compose exec test-runner mvn test -Dbrowser=Firefox

      - name: Clean up
        run: docker-compose down